# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmyqtrOXlUv-7-r0WmsXj4ZaDrADbNjx
"""

import matplotlib.pyplot as plt
import pandas as pd

# Read CSV file
df= pd.read_csv('Annual CO2 Final.csv')

# Get unique country codes
countries = df['Code'].unique()

fig, ax = plt.subplots(figsize=(50, 25))
for c in countries:
  x = df.loc[df['Code'] == c, 'Year']
  y = df.loc[df['Code'] == c, 'Annual CO₂ emissions']

  ax.fill_between(x, y, label = c, alpha=0.5) # Use fill_between for area chart

# Disable scientific notation
ax.ticklabel_format(style='plain')

plt.legend()

ax.set_xlabel('Years')
ax.set_ylabel('Annual CO₂ emissions')
ax.set_title('Annual CO₂ emissions/ Year')
plt.show()