# -*- coding: utf-8 -*-
"""Consumption of Energy Per Capita

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GS2FMKtwsV5Zfpy_AEUgWfJBzDXNlzvQ
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

data = pd.read_csv("consumption of energy per capita FINAL FINAL.csv")

countries = []
i = 0
while i < len(data['Code']):
  country = data["Code"][i]
  if country not in countries:
    countries.append(data['Code'][i])
  i = i + 1

fig, ax = plt.subplots(figsize=(50, 25))
for c in countries:
  x = data.loc[data['Code'] == c, 'Year']
  y = data.loc[data['Code'] == c, 'Primary energy consumption per capita (kWh/person)']

  plt.plot(x, y, label = c)
  plt.legend()

ax.set_xlabel('Years')
ax.set_ylabel('Primary energy consumption per capita (kWh/person)')
ax.set_title('Consumption of Energy Per Capita')